package net.zerobuilder.compiler;

import com.google.common.collect.ImmutableList;
import org.junit.Test;

import javax.tools.JavaFileObject;

import static com.google.common.truth.Truth.assertAbout;
import static com.google.testing.compile.JavaFileObjects.forSourceLines;
import static com.google.testing.compile.JavaSourcesSubjectFactory.javaSources;
import static net.zerobuilder.compiler.test_util.GeneratedLines.GENERATED_ANNOTATION;

public class RecyclingBeanTest {

  @Test
  public void recycling() {
    JavaFileObject businessAnalyst = forSourceLines("beans.BusinessAnalyst",
        "package beans;",
        "import net.zerobuilder.*;",
        "import java.util.List;",
        "import java.util.ArrayList;",
        "",
        "@Builders(recycle = true)",
        "@Goal(updater = true, builderAccess = AccessLevel.PACKAGE)",
        "public class BusinessAnalyst {",
        "  private String name;",
        "  private List<String> notes;",
        "  public String getName() { return name; }",
        "  public void setName(String name) { this.name = name; }",
        "  @Step(nullPolicy = NullPolicy.REJECT) public List<String> getNotes() {",
        "    if (notes == null) notes = new ArrayList<>();",
        "    return notes;",
        "  }",
        "}");
    JavaFileObject expected =
        forSourceLines("beans.BusinessAnalystBuilders",
            "package beans;",
            "import javax.annotation.Generated;",
            "",
            GENERATED_ANNOTATION,
            "public final class BusinessAnalystBuilders {",
            "  private static final ThreadLocal<BusinessAnalystUpdater> businessAnalystUpdater = new ThreadLocal<BusinessAnalystUpdater>() {",
            "    @Override",
            "    protected BusinessAnalystUpdater initialValue() {",
            "      return new BusinessAnalystUpdater();",
            "    }",
            "  }",
            "",
            "  private static final ThreadLocal<BusinessAnalystBuilderImpl> businessAnalystBuilderImpl = new ThreadLocal<BusinessAnalystBuilderImpl>() {",
            "    @Override",
            "    protected BusinessAnalystBuilderImpl initialValue() {",
            "      return new BusinessAnalystBuilderImpl();",
            "    }",
            "  }",
            "",
            "  private BusinessAnalystBuilders() {",
            "    throw new UnsupportedOperationException(\"no instances\");",
            "  }",
            "",
            "  public static BusinessAnalystUpdater businessAnalystUpdater(BusinessAnalyst businessAnalyst) {",
            "    if (businessAnalyst.getNotes() == null) {",
            "      throw new NullPointerException(\"notes\");",
            "    }",
            "    BusinessAnalystUpdater _updater = businessAnalystUpdater.get();",
            "    if (_updater._currently_in_use) {",
            "      businessAnalystUpdater.remove();",
            "      _updater = businessAnalystUpdater.get();",
            "    }",
            "    _updater.businessAnalyst = new BusinessAnalyst();",
            "    _updater._currently_in_use = true;",
            "    _updater.businessAnalyst.setName(businessAnalyst.getName());",
            "    for (String string : businessAnalyst.getNotes()) {",
            "      _updater.businessAnalyst.getNotes().add(string);",
            "    }",
            "    return _updater;",
            "  }",
            "",
            "  static BusinessAnalystBuilder.Name businessAnalystBuilder() {",
            "    BusinessAnalystBuilderImpl _builder = businessAnalystBuilderImpl.get();",
            "    if (_builder._currently_in_use) {",
            "      businessAnalystBuilderImpl.remove();",
            "      _builder = businessAnalystBuilderImpl.get();",
            "    }",
            "    _builder.businessAnalyst = new BusinessAnalyst();",
            "    _builder._currently_in_use = true;",
            "    return _builder;",
            "  }",
            "",
            "  public static final class BusinessAnalystUpdater {",
            "    private boolean _currently_in_use;",
            "    private BusinessAnalyst businessAnalyst;",
            "    private BusinessAnalystUpdater() {}",
            "",
            "    public BusinessAnalystUpdater name(String name) {",
            "      this.businessAnalyst.setName(name);",
            "      return this;",
            "    }",
            "",
            "    public BusinessAnalystUpdater notes(Iterable<? extends String> notes) {",
            "      if (notes == null) {",
            "        throw new NullPointerException(\"notes\");",
            "      }",
            "      this.businessAnalyst.getNotes().clear();",
            "      for (String string : notes) {",
            "        this.businessAnalyst.getNotes().add(string);",
            "      }",
            "      return this;",
            "    }",
            "",
            "    public BusinessAnalyst done() {",
            "      this._currently_in_use = false;",
            "      BusinessAnalyst _businessAnalyst = this.businessAnalyst;",
            "      this.businessAnalyst = null;",
            "      return _businessAnalyst;",
            "    }",
            "  }",
            "",
            "  private static final class BusinessAnalystBuilderImpl",
            "        implements BusinessAnalystBuilder.Name, BusinessAnalystBuilder.Notes {",
            "    private boolean _currently_in_use;",
            "    private BusinessAnalyst businessAnalyst;",
            "    BusinessAnalystBuilderImpl() {}",
            "",
            "    @Override public BusinessAnalystBuilder.Notes name(String name) {",
            "      this.businessAnalyst.setName(name);",
            "      return this;",
            "    }",
            "",
            "    @Override public BusinessAnalyst notes(Iterable<? extends String> notes) {",
            "      if (notes == null) {",
            "        throw new NullPointerException(\"notes\");",
            "      }",
            "      for (String string : notes) {",
            "        this.businessAnalyst.getNotes().add(string);",
            "      }",
            "      this._currently_in_use = false;",
            "      BusinessAnalyst _businessAnalyst = this.businessAnalyst;",
            "      this.businessAnalyst = null;",
            "      return _businessAnalyst;",
            "    }",
            "  }",
            "",
            "  public static final class BusinessAnalystBuilder {",
            "    private BusinessAnalystBuilder() {",
            "      throw new UnsupportedOperationException(\"no instances\");",
            "    }",
            "    public interface Name { Notes name(String name); }",
            "    public interface Notes {",
            "      BusinessAnalyst notes(Iterable<? extends String> notes);",
            "    }",
            "  }",
            "}");
    assertAbout(javaSources()).that(ImmutableList.of(businessAnalyst))
        .processedWith(new ZeroProcessor())
        .compilesWithoutError()
        .and().generatesSources(expected);
  }
}
