#!/bin/bash

if [[ ! -d ../../compiler/target ]]; then
  mkdir -p ../../compiler/target
fi

function find_jar {
  find ../../compiler/target -maxdepth 1 -name "*.jar" | \
    grep -E '.*/zerobuilder-[0123456789.]+(-SNAPSHOT)?.jar'
}

THE_JAR=`find_jar`

if [[ -z "$THE_JAR" ]]; then
  mvn package -f ../../pom.xml
  THE_JAR=`find_jar`
fi

if [[ -z "$THE_JAR" ]]; then
  echo "[ERROR] zerobuilder jar not found"
  exit 1
fi

if [[ ! -f target/classes/net/zerobuilder/examples/javac/JavaMan.class ]]; then
  rm -rf target
  mkdir -p target/classes
  mkdir -p target/generated-sources/annotations
  javac -source 8 -target 8 \
        -cp $THE_JAR \
        -d target/classes \
        -s target/generated-sources/annotations \
        src/net/zerobuilder/examples/javac/JavaMan.java  
fi

java -cp target/classes \
     net.zerobuilder.examples.javac.JavaMan
