#!/bin/bash
if [[ -z "$1" ]]; then echo arg: version; exit 1; fi
mvn versions:set -DnewVersion=$1 &>/dev/null
if [[ "$1" =~ .*SNAPSHOT ]]; then
  mvn clean install
else
  mvn clean install -Psonatype-oss-release
fi
mv dependency-reduced-pom.xml target/zerobuilder-$1.pom
mv pom.xml.versionsBackup pom.xml
if ! [[ "$1" =~ .*SNAPSHOT ]]; then
  cd target
  gpg -ab zerobuilder-$1.pom
fi
